<a href="https://colab.research.google.com/github/saoalonsort/Natural-Language-Processing-KI-Campus/blob/main/Pr%C3%A1ctica_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

In [13]:
pd.DataFrame({'Sales': [4000, 8000, 16000, 32000, 18000, 30000],
              'Most sold Product': ['Laptop', 'Laptop', 'Laptop', 'Tablet', 'Computer', 'Laptop']},
             index=[2000, 2005, 2010, 2015, 2020, 2025])

      Sales Most sold Product
2000   4000            Laptop
2005   8000            Laptop
2010  16000            Laptop
2015  32000            Tablet
2020  18000          Computer
2025  30000            Laptop

In [14]:
pd.Series([8, 4, 2, 3], index=['Palabras', 'Sílabas', 'Comas', 'Puntos'], name='Texto')

Palabras    8
Sílabas     4
Comas       2
Puntos      3
Name: Texto, dtype: int64

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
import pandas as pd

# Ruta donde guardaste el archivo
datos = '/content/drive/MyDrive/Colab Notebooks/My project pandas/car_price_dataset.csv'

# Leer el archivo
datos = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/My project pandas/car_price_dataset.csv')

In [17]:
datos.shape

(2000, 11)

In [18]:
datos.head()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35

In [19]:
datos['Brand']

0          Ford
1       Hyundai
2           BMW
3       Hyundai
4       Hyundai
         ...
1995    Hyundai
1996     Toyota
1997    Hyundai
1998        BMW
1999      Honda
Name: Brand, Length: 2000, dtype: object

In [20]:
datos.iloc[7]

Car_ID                  8
Brand                 BMW
Model_Year           2022
Engine_Size           3.9
Fuel_Type          Petrol
Transmission    Automatic
Mileage            195932
Doors                   4
Owner_Count             1
Horsepower            369
Price             61707.4
Name: 7, dtype: object

In [21]:
datos[0:8]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
5,6,Honda,2023,3.5,Petrol,Automatic,94110,2,4,173,54182.50
6,7,BMW,2016,2.3,Petrol,Manual,7810,2,3,267,52140.50
7,8,BMW,2022,3.9,Petrol,Automatic,195932,4,1,369,61707.40

In [22]:
datos.iloc[:10, 5]

0       Manual
1       Manual
2       Manual
3    Automatic
4       Manual
5    Automatic
6       Manual
7    Automatic
8       Manual
9       Manual
Name: Transmission, dtype: object

In [23]:
datos.iloc[[0, 3, 6], 5]

0       Manual
3    Automatic
6       Manual
Name: Transmission, dtype: object

In [24]:
datos.iloc[-678]

Car_ID              1323
Brand             Toyota
Model_Year          2021
Engine_Size          1.5
Fuel_Type       Electric
Transmission      Manual
Mileage            97508
Doors                  2
Owner_Count            2
Horsepower           315
Price            48990.6
Name: 1322, dtype: object

In [25]:
datos.loc[5, 'Brand']

'Honda'

In [26]:
datos.loc[:6, ['Brand', 'Model_Year', 'Transmission']]

     Brand  Model_Year Transmission
0     Ford        2023       Manual
1  Hyundai        2018       Manual
2      BMW        2008       Manual
3  Hyundai        2017    Automatic
4  Hyundai        2012       Manual
5    Honda        2023    Automatic
6      BMW        2016       Manual

In [27]:
datos.loc[:24, ['Brand', 'Engine_Size', 'Fuel_Type']]

      Brand  Engine_Size Fuel_Type
0      Ford          1.2    Hybrid
1   Hyundai          3.2  Electric
2       BMW          2.2    Diesel
3   Hyundai          2.2    Petrol
4   Hyundai          2.4  Electric
5     Honda          3.5    Petrol
6       BMW          2.3    Petrol
7       BMW          3.9    Petrol
8       BMW          2.6  Electric
9   Hyundai          1.3  Electric
10     Ford          4.1    Petrol
11      BMW          2.1    Diesel
12    Tesla          2.7    Petrol
13  Hyundai          3.7    Diesel
14    Honda          2.3    Petrol
15     Ford          1.2    Hybrid
16    Tesla          2.5    Petrol
17    Tesla          4.8    Petrol
18    Honda          3.6  Electric
19     Ford          3.7    Diesel
20  Hyundai          3.5    Hybrid
21   Toyota          1.8    Diesel
22     Ford          2.7    Hybrid
23    Honda          4.0    Petrol
24    Tesla          1.4  Electric

In [28]:
datos.set_index('Car_ID')

,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
Car_ID,,,,,,,,,,
1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...
1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40
1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65
2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

In [29]:
datos['Brand'] == 'Toyota'

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996     True
1997    False
1998    False
1999    False
Name: Brand, Length: 2000, dtype: bool

In [30]:
datos. loc[datos['Brand'] == 'Toyota']

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
21,22,Toyota,2021,1.8,Diesel,Automatic,191023,2,1,154,37807.85
27,28,Toyota,2023,2.7,Electric,Manual,15435,2,4,216,55129.25
28,29,Toyota,2013,4.9,Diesel,Automatic,189983,3,3,150,47514.85
40,41,Toyota,2023,2.1,Petrol,Automatic,187877,2,1,273,45931.15
45,46,Toyota,2012,3.6,Petrol,Automatic,141984,4,4,212,42371.80
...,...,...,...,...,...,...,...,...,...,...,...
1966,1967,Toyota,2010,2.8,Petrol,Automatic,124640,2,4,374,48402.00
1968,1969,Toyota,2021,1.8,Electric,Automatic,47687,2,2,155,44018.65
1969,1970,Toyota,2012,1.0,Petrol,Automatic,182175,4,3,95,20840.25
1986,1987,Toyota,2006,4.6,Petrol,Manual,65110,4,3,329,53916.50
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80

In [31]:
datos.loc[(datos['Brand'] == 'Toyota') & (datos['Transmission'] == 'Automatic')]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
21,22,Toyota,2021,1.8,Diesel,Automatic,191023,2,1,154,37807.85
28,29,Toyota,2013,4.9,Diesel,Automatic,189983,3,3,150,47514.85
40,41,Toyota,2023,2.1,Petrol,Automatic,187877,2,1,273,45931.15
45,46,Toyota,2012,3.6,Petrol,Automatic,141984,4,4,212,42371.80
48,49,Toyota,2007,1.3,Hybrid,Automatic,164869,4,3,89,18911.55
...,...,...,...,...,...,...,...,...,...,...,...
1946,1947,Toyota,2019,4.0,Hybrid,Automatic,90637,2,2,390,67042.15
1960,1961,Toyota,2018,2.7,Petrol,Automatic,24346,2,2,162,47952.70
1966,1967,Toyota,2010,2.8,Petrol,Automatic,124640,2,4,374,48402.00
1968,1969,Toyota,2021,1.8,Electric,Automatic,47687,2,2,155,44018.65
1969,1970,Toyota,2012,1.0,Petrol,Automatic,182175,4,3,95,20840.25

In [32]:
datos.loc[(datos['Brand'] == 'Toyota') | (datos['Fuel_Type'] == 'Hybrid')]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
15,16,Ford,2023,1.2,Hybrid,Automatic,75864,2,3,226,46896.80
20,21,Hyundai,2016,3.5,Hybrid,Automatic,71188,4,4,122,47823.60
21,22,Toyota,2021,1.8,Diesel,Automatic,191023,2,1,154,37807.85
22,23,Ford,2009,2.7,Hybrid,Automatic,86718,2,2,342,50356.10
...,...,...,...,...,...,...,...,...,...,...,...
1986,1987,Toyota,2006,4.6,Petrol,Manual,65110,4,3,329,53916.50
1988,1989,Honda,2009,2.3,Hybrid,Manual,50213,3,2,271,46463.35
1989,1990,Tesla,2012,4.3,Hybrid,Manual,198065,2,1,331,52950.75
1994,1995,Ford,2020,2.4,Hybrid,Manual,167887,4,4,168,39122.65
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80

In [33]:
datos.loc[datos['Brand'].isin(['Ford', 'Toyota', 'BMW'])]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
6,7,BMW,2016,2.3,Petrol,Manual,7810,2,3,267,52140.50
7,8,BMW,2022,3.9,Petrol,Automatic,195932,4,1,369,61707.40
8,9,BMW,2010,2.6,Electric,Manual,76688,3,1,238,44992.60
...,...,...,...,...,...,...,...,...,...,...,...
1990,1991,BMW,2011,3.4,Petrol,Manual,17938,3,1,254,50765.10
1993,1994,Ford,2022,4.4,Electric,Manual,89390,4,4,179,53926.50
1994,1995,Ford,2020,2.4,Hybrid,Manual,167887,4,4,168,39122.65
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65

In [34]:
datos['Sales'] = 'NaN'
datos['Sales']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1995    NaN
1996    NaN
1997    NaN
1998    NaN
1999    NaN
Name: Sales, Length: 2000, dtype: object

In [35]:
datos.loc[datos['Brand'].isnull()]

Empty DataFrame
Columns: [Car_ID, Brand, Model_Year, Engine_Size, Fuel_Type, Transmission, Mileage, Doors, Owner_Count, Horsepower, Price, Sales]
Index: []

In [36]:
datos.loc[datos['Brand'].notnull()]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,Sales
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25,NaN
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60,NaN
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40,NaN
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70,NaN
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35,NaN
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80,NaN
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40,NaN
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65,NaN
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70,NaN

In [37]:
datos['indice_nuevo'] = range(len(datos), 0, -1)
datos['indice_nuevo']

0       2000
1       1999
2       1998
3       1997
4       1996
        ...
1995       5
1996       4
1997       3
1998       2
1999       1
Name: indice_nuevo, Length: 2000, dtype: int64

In [38]:
datos['Brand'].describe()

count       2000
unique         6
top       Toyota
freq         352
Name: Brand, dtype: object

In [39]:
datos['Transmission'].describe()

count          2000
unique            2
top       Automatic
freq           1018
Name: Transmission, dtype: object

In [40]:
datos['Fuel_Type'].describe()

count       2000
unique         4
top       Diesel
freq         537
Name: Fuel_Type, dtype: object

In [41]:
datos['Mileage'].mean()

np.float64(100736.9565)

In [42]:
datos['Mileage'].median()

100590.5

In [43]:
datos['Brand'].unique()

array(['Ford', 'Hyundai', 'BMW', 'Honda', 'Tesla', 'Toyota'], dtype=object)

In [44]:
datos['Brand'].value_counts()

Brand
Toyota     352
Hyundai    337
Tesla      330
Honda      329
Ford       326
BMW        326
Name: count, dtype: int64

In [45]:
datos_mileage_mean = datos['Mileage'].mean()
datos['Mileage'].map(lambda p: p - datos_mileage_mean)

0       79898.0435
1      -65108.9565
2      -26064.9565
3      -49490.9565
4       46496.0435
           ...
1995    54296.0435
1996   -75692.9565
1997     3635.0435
1998    57310.0435
1999   -81030.9565
Name: Mileage, Length: 2000, dtype: float64

In [46]:
datos_mileage_median = datos['Mileage'].median()
datos['Mileage'].map(lambda p: p - datos_mileage_median)

0       80044.5
1      -64962.5
2      -25918.5
3      -49344.5
4       46642.5
         ...
1995    54442.5
1996   -75546.5
1997     3781.5
1998    57456.5
1999   -80884.5
Name: Mileage, Length: 2000, dtype: float64

In [47]:
def remean_mileage(row):
  row['Mileage'] = row['Mileage'] - datos_mileage_mean
  return row

datos.apply(remean_mileage, axis='columns')

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,Sales,indice_nuevo
0,1,Ford,2023,1.2,Hybrid,Manual,79898.0435,4,3,82,34309.25,NaN,2000
1,2,Hyundai,2018,3.2,Electric,Manual,-65108.9565,2,4,259,55153.60,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,-26064.9565,3,2,333,41894.40,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,-49490.9565,4,4,381,54046.70,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,46496.0435,3,4,290,38010.35,NaN,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,54296.0435,2,3,310,61734.35,NaN,5
1996,1997,Toyota,2023,1.4,Petrol,Manual,-75692.9565,2,4,271,48467.80,NaN,4
1997,1998,Hyundai,2022,4.1,Diesel,Manual,3635.0435,4,3,191,55714.40,NaN,3
1998,1999,BMW,2020,4.4,Diesel,Automatic,57310.0435,4,1,186,53222.65,NaN,2
1999,2000,Honda,2012,1.7,Electric,Automatic,-81030.9565,3,1,165,40687.70,NaN,1

In [48]:
def remean_mileage(row):
  row['Mileage'] = row['Mileage'] - datos_mileage_median
  return row

datos.apply(remean_mileage, axis='columns')

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,Sales,indice_nuevo
0,1,Ford,2023,1.2,Hybrid,Manual,80044.5,4,3,82,34309.25,NaN,2000
1,2,Hyundai,2018,3.2,Electric,Manual,-64962.5,2,4,259,55153.60,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,-25918.5,3,2,333,41894.40,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,-49344.5,4,4,381,54046.70,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,46642.5,3,4,290,38010.35,NaN,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,54442.5,2,3,310,61734.35,NaN,5
1996,1997,Toyota,2023,1.4,Petrol,Manual,-75546.5,2,4,271,48467.80,NaN,4
1997,1998,Hyundai,2022,4.1,Diesel,Manual,3781.5,4,3,191,55714.40,NaN,3
1998,1999,BMW,2020,4.4,Diesel,Automatic,57456.5,4,1,186,53222.65,NaN,2
1999,2000,Honda,2012,1.7,Electric,Automatic,-80884.5,3,1,165,40687.70,NaN,1

In [49]:
datos.head()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,Sales,indice_nuevo
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25,NaN,2000
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35,NaN,1996

In [50]:
datos_mileage_mean = datos['Mileage'].mean()
datos['Mileage'] - datos_mileage_mean

0       79898.0435
1      -65108.9565
2      -26064.9565
3      -49490.9565
4       46496.0435
           ...
1995    54296.0435
1996   -75692.9565
1997     3635.0435
1998    57310.0435
1999   -81030.9565
Name: Mileage, Length: 2000, dtype: float64

In [51]:
datos['Brand'] + "-" + datos['Transmission']

0             Ford-Manual
1          Hyundai-Manual
2              BMW-Manual
3       Hyundai-Automatic
4          Hyundai-Manual
              ...
1995       Hyundai-Manual
1996        Toyota-Manual
1997       Hyundai-Manual
1998        BMW-Automatic
1999      Honda-Automatic
Length: 2000, dtype: object

In [62]:
datos.groupby('Brand')['Price'].count()

Brand
BMW        326
Ford       326
Honda      329
Hyundai    337
Tesla      330
Toyota     352
Name: Price, dtype: int64

In [63]:
datos.groupby('Brand')['Price'].min()

Brand
BMW        21956.60
Ford       21838.20
Honda      23455.85
Hyundai    22859.25
Tesla      21525.15
Toyota     18911.55
Name: Price, dtype: float64

In [64]:
datos.groupby(['Brand', 'Transmission'])['Price'].count()

Brand    Transmission
BMW      Automatic       166
         Manual          160
Ford     Automatic       160
         Manual          166
Honda    Automatic       169
         Manual          160
Hyundai  Automatic       165
         Manual          172
Tesla    Automatic       154
         Manual          176
Toyota   Automatic       204
         Manual          148
Name: Price, dtype: int64

In [66]:
datos.groupby(['Brand', 'Transmission', 'Fuel_Type'])['Price'].agg([len, min, max])

/tmp/ipykernel_2431/992431278.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  datos.groupby(['Brand', 'Transmission', 'Fuel_Type'])['Price'].agg([len, min, max])
/tmp/ipykernel_2431/992431278.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  datos.groupby(['Brand', 'Transmission', 'Fuel_Type'])['Price'].agg([len, min, max])

                                len       min       max
Brand   Transmission Fuel_Type
BMW     Automatic    Diesel      54  23719.50  61594.75
                     Electric    35  30355.70  66001.20
                     Hybrid      44  28721.45  65628.65
                     Petrol      33  32855.60  66928.75
        Manual       Diesel      45  21956.60  65408.15
                     Electric    40  27120.10  66484.90
                     Hybrid      35  26044.30  67795.40
                     Petrol      40  34422.60  64039.75
Ford    Automatic    Diesel      43  22753.25  67484.50
                     Electric    41  23833.05  68405.50
                     Hybrid      42  24942.60  59494.15
                     Petrol      34  27974.15  66292.05
        Manual       Diesel      43  21838.20  64310.90
                     Electric    43  26968.20  67866.00
                     Hybrid      39  28271.10  61171.70
                     Petrol      41  25805.60  69974.95
Honda   Automatic    Diesel      53  26078.25  64542.20
                     Electric    44  26390.75  69079.30
                     Hybrid      33  33608.35  61843.45
                     Petrol      39  23455.85  67906.50
        Manual       Diesel      42  36494.80  64103.20
                     Electric    29  31616.55  64624.30
                     Hybrid      36  31022.15  68763.00
                     Petrol      53  29125.55  69174.60
Hyundai Automatic    Diesel      44  27019.10  68727.25
                     Electric    37  25540.95  65440.85
                     Hybrid      35  27267.50  67918.20
                     Petrol      49  27636.45  72267.80
        Manual       Diesel      47  31728.50  64835.80
                     Electric    46  23636.00  60254.35
                     Hybrid      40  22859.25  63671.10
                     Petrol      39  33949.95  67813.65
Tesla   Automatic    Diesel      37  30900.90  70167.60
                     Electric    42  21525.15  63374.30
                     Hybrid      35  32725.70  65917.30
                     Petrol      40  22462.20  67784.45
        Manual       Diesel      46  29599.95  63310.25
                     Electric    31  27123.60  65814.90
                     Hybrid      42  30161.50  63253.20
                     Petrol      57  27541.10  64881.45
Toyota  Automatic    Diesel      53  27241.45  61327.30
                     Electric    55  26532.15  62628.60
                     Hybrid      52  18911.55  67042.15
                     Petrol      44  20840.25  62966.40
        Manual       Diesel      30  32713.50  63814.70
                     Electric    41  23909.00  61221.35
                     Hybrid      35  28026.05  64192.70
                     Petrol      42  26378.20  65606.90

In [80]:
brand_price = datos.groupby(['Brand', 'Fuel_Type'])['Price'].agg([len, 'min', 'max'])
brand_price

                   len       min       max
Brand   Fuel_Type
BMW     Diesel      99  21956.60  65408.15
        Electric    75  27120.10  66484.90
        Hybrid      79  26044.30  67795.40
        Petrol      73  32855.60  66928.75
Ford    Diesel      86  21838.20  67484.50
        Electric    84  23833.05  68405.50
        Hybrid      81  24942.60  61171.70
        Petrol      75  25805.60  69974.95
Honda   Diesel      95  26078.25  64542.20
        Electric    73  26390.75  69079.30
        Hybrid      69  31022.15  68763.00
        Petrol      92  23455.85  69174.60
Hyundai Diesel      91  27019.10  68727.25
        Electric    83  23636.00  65440.85
        Hybrid      75  22859.25  67918.20
        Petrol      88  27636.45  72267.80
Tesla   Diesel      83  29599.95  70167.60
        Electric    73  21525.15  65814.90
        Hybrid      77  30161.50  65917.30
        Petrol      97  22462.20  67784.45
Toyota  Diesel      83  27241.45  63814.70
        Electric    96  23909.00  62628.60
        Hybrid      87  18911.55  67042.15
        Petrol      86  20840.25  65606.90

In [81]:
table = brand_price.index
type(table)

pandas.core.indexes.multi.MultiIndex

In [82]:
brand_price.reset_index()

      Brand Fuel_Type  len       min       max
0       BMW    Diesel   99  21956.60  65408.15
1       BMW  Electric   75  27120.10  66484.90
2       BMW    Hybrid   79  26044.30  67795.40
3       BMW    Petrol   73  32855.60  66928.75
4      Ford    Diesel   86  21838.20  67484.50
5      Ford  Electric   84  23833.05  68405.50
6      Ford    Hybrid   81  24942.60  61171.70
7      Ford    Petrol   75  25805.60  69974.95
8     Honda    Diesel   95  26078.25  64542.20
9     Honda  Electric   73  26390.75  69079.30
10    Honda    Hybrid   69  31022.15  68763.00
11    Honda    Petrol   92  23455.85  69174.60
12  Hyundai    Diesel   91  27019.10  68727.25
13  Hyundai  Electric   83  23636.00  65440.85
14  Hyundai    Hybrid   75  22859.25  67918.20
15  Hyundai    Petrol   88  27636.45  72267.80
16    Tesla    Diesel   83  29599.95  70167.60
17    Tesla  Electric   73  21525.15  65814.90
18    Tesla    Hybrid   77  30161.50  65917.30
19    Tesla    Petrol   97  22462.20  67784.45
20   Toyota    Diesel   83  27241.45  63814.70
21   Toyota  Electric   96  23909.00  62628.60
22   Toyota    Hybrid   87  18911.55  67042.15
23   Toyota    Petrol   86  20840.25  65606.90

In [86]:
table = brand_price.reset_index()
table.sort_values(by='len', ascending=False)

      Brand Fuel_Type  len       min       max
0       BMW    Diesel   99  21956.60  65408.15
19    Tesla    Petrol   97  22462.20  67784.45
21   Toyota  Electric   96  23909.00  62628.60
8     Honda    Diesel   95  26078.25  64542.20
11    Honda    Petrol   92  23455.85  69174.60
12  Hyundai    Diesel   91  27019.10  68727.25
15  Hyundai    Petrol   88  27636.45  72267.80
22   Toyota    Hybrid   87  18911.55  67042.15
4      Ford    Diesel   86  21838.20  67484.50
23   Toyota    Petrol   86  20840.25  65606.90
5      Ford  Electric   84  23833.05  68405.50
16    Tesla    Diesel   83  29599.95  70167.60
13  Hyundai  Electric   83  23636.00  65440.85
20   Toyota    Diesel   83  27241.45  63814.70
6      Ford    Hybrid   81  24942.60  61171.70
2       BMW    Hybrid   79  26044.30  67795.40
18    Tesla    Hybrid   77  30161.50  65917.30
14  Hyundai    Hybrid   75  22859.25  67918.20
1       BMW  Electric   75  27120.10  66484.90
7      Ford    Petrol   75  25805.60  69974.95
3       BMW    Petrol   73  32855.60  66928.75
9     Honda  Electric   73  26390.75  69079.30
17    Tesla  Electric   73  21525.15  65814.90
10    Honda    Hybrid   69  31022.15  68763.00

In [88]:
brand_price.sort_index()

                   len       min       max
Brand   Fuel_Type
BMW     Diesel      99  21956.60  65408.15
        Electric    75  27120.10  66484.90
        Hybrid      79  26044.30  67795.40
        Petrol      73  32855.60  66928.75
Ford    Diesel      86  21838.20  67484.50
        Electric    84  23833.05  68405.50
        Hybrid      81  24942.60  61171.70
        Petrol      75  25805.60  69974.95
Honda   Diesel      95  26078.25  64542.20
        Electric    73  26390.75  69079.30
        Hybrid      69  31022.15  68763.00
        Petrol      92  23455.85  69174.60
Hyundai Diesel      91  27019.10  68727.25
        Electric    83  23636.00  65440.85
        Hybrid      75  22859.25  67918.20
        Petrol      88  27636.45  72267.80
Tesla   Diesel      83  29599.95  70167.60
        Electric    73  21525.15  65814.90
        Hybrid      77  30161.50  65917.30
        Petrol      97  22462.20  67784.45
Toyota  Diesel      83  27241.45  63814.70
        Electric    96  23909.00  62628.60
        Hybrid      87  18911.55  67042.15
        Petrol      86  20840.25  65606.90

In [91]:
brand_price.sort_values(['Brand', 'min'])

                   len       min       max
Brand   Fuel_Type
BMW     Diesel      99  21956.60  65408.15
        Hybrid      79  26044.30  67795.40
        Electric    75  27120.10  66484.90
        Petrol      73  32855.60  66928.75
Ford    Diesel      86  21838.20  67484.50
        Electric    84  23833.05  68405.50
        Hybrid      81  24942.60  61171.70
        Petrol      75  25805.60  69974.95
Honda   Petrol      92  23455.85  69174.60
        Diesel      95  26078.25  64542.20
        Electric    73  26390.75  69079.30
        Hybrid      69  31022.15  68763.00
Hyundai Hybrid      75  22859.25  67918.20
        Electric    83  23636.00  65440.85
        Diesel      91  27019.10  68727.25
        Petrol      88  27636.45  72267.80
Tesla   Electric    73  21525.15  65814.90
        Petrol      97  22462.20  67784.45
        Diesel      83  29599.95  70167.60
        Hybrid      77  30161.50  65917.30
Toyota  Hybrid      87  18911.55  67042.15
        Petrol      86  20840.25  65606.90
        Electric    96  23909.00  62628.60
        Diesel      83  27241.45  63814.70

In [93]:
datos.dtypes

Car_ID            int64
Brand            object
Model_Year        int64
Engine_Size     float64
Fuel_Type        object
Transmission     object
Mileage           int64
Doors             int64
Owner_Count       int64
Horsepower        int64
Price           float64
Sales            object
indice_nuevo      int64
dtype: object

In [96]:
datos['Price'].astype('float64')

0       34309.25
1       55153.60
2       41894.40
3       54046.70
4       38010.35
          ...
1995    61734.35
1996    48467.80
1997    55714.40
1998    53222.65
1999    40687.70
Name: Price, Length: 2000, dtype: float64

In [97]:
datos.index.dtype

dtype('int64')

In [98]:
datos[pd.isnull(datos['Price'])]

Empty DataFrame
Columns: [Car_ID, Brand, Model_Year, Engine_Size, Fuel_Type, Transmission, Mileage, Doors, Owner_Count, Horsepower, Price, Sales, indice_nuevo]
Index: []

In [99]:
datos['Fuel_Type'].replace("Petrol", "Gasolina")

0         Hybrid
1       Electric
2         Diesel
3       Gasolina
4       Electric
          ...
1995      Diesel
1996    Gasolina
1997      Diesel
1998      Diesel
1999    Electric
Name: Fuel_Type, Length: 2000, dtype: object

In [100]:
datos.rename(columns={'Mileage': 'Kilometraje'})

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Kilometraje,Doors,Owner_Count,Horsepower,Price,Sales,indice_nuevo
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25,NaN,2000
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35,NaN,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35,NaN,5
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80,NaN,4
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40,NaN,3
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65,NaN,2
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70,NaN,1

In [101]:
datos.rename(index={0: 'Uno', 1: 'Dos'})

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,Sales,indice_nuevo
Uno,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25,NaN,2000
Dos,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35,NaN,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35,NaN,5
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80,NaN,4
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40,NaN,3
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65,NaN,2
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70,NaN,1

In [103]:
datos.rename_axis('Index', axis='rows').rename_axis('Features', axis='columns')

Features,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,Sales,indice_nuevo
Index,,,,,,,,,,,,,
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25,NaN,2000
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35,NaN,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35,NaN,5
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80,NaN,4
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40,NaN,3
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65,NaN,2
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70,NaN,1